import {NgModule} from '@angular/core';
import {
  MatButtonModule,
  MatCardModule,
  MatToolbarModule,
  MatInputModule,
  MatMenuModule,
  MatListModule,
  MatDialogModule,
  MatIconModule,
  MatButtonToggleModule,
  MatTableModule,
  MatDividerModule,
  MatSelectModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatSidenavModule,
  MatSnackBarModule,
  MatRippleModule,
  MatExpansionModule,
  MatStepperModule,
  MatGridListModule,
  MatTabsModule,
  MatTreeModule,
  MatChipsModule,
  MatCheckboxModule,
  MatProgressSpinnerModule,
  MatProgressBarModule,
  MatSlideToggleModule,
} from '@angular/material';
import { CdkTableModule } from '@angular/cdk/table';
import { LayoutModule } from '@angular/cdk/layout';


@NgModule({
  imports: [
    MatButtonModule,
    MatCardModule,
    MatToolbarModule,
    MatInputModule,
    MatMenuModule,
    MatListModule,
    MatDialogModule,
    MatIconModule,
    MatButtonToggleModule,
    MatTableModule,
    CdkTableModule,
    MatDividerModule,
    MatSelectModule,
    MatTreeModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSidenavModule,
    MatSnackBarModule,
    MatRippleModule,
    MatExpansionModule,
    LayoutModule,
    MatStepperModule,
    MatGridListModule,
    MatTabsModule,
    MatChipsModule,
    MatCheckboxModule,
    MatProgressSpinnerModule,
    MatSlideToggleModule,
  ],
  exports: [
    MatButtonModule,
    MatCardModule,
    MatToolbarModule,
    MatInputModule,
    MatMenuModule,
    MatListModule,
    MatDialogModule,
    MatIconModule,
    MatButtonToggleModule,
    MatTableModule,
    CdkTableModule,
    MatDividerModule,
    MatSelectModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSidenavModule,
    MatSnackBarModule,
    MatRippleModule,
    MatExpansionModule,
    LayoutModule,
    MatStepperModule,
    MatGridListModule,
    MatTabsModule,
    MatChipsModule,
    MatCheckboxModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatTreeModule,
    MatSlideToggleModule,
  ],
  declarations: []
})
export class MaterialModule {}
